// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chrono.proto

package chrono

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Time struct {
	ProtoTime            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=proto_time,json=protoTime,proto3" json:"proto_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fd0f9191623b5fb, []int{0}
}

func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (m *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(m, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetProtoTime() *timestamp.Timestamp {
	if m != nil {
		return m.ProtoTime
	}
	return nil
}

type Duration struct {
	ProtoDuration        *duration.Duration `protobuf:"bytes,1,opt,name=proto_duration,json=protoDuration,proto3" json:"proto_duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Duration) Reset()         { *m = Duration{} }
func (m *Duration) String() string { return proto.CompactTextString(m) }
func (*Duration) ProtoMessage()    {}
func (*Duration) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fd0f9191623b5fb, []int{1}
}

func (m *Duration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Duration.Unmarshal(m, b)
}
func (m *Duration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Duration.Marshal(b, m, deterministic)
}
func (m *Duration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Duration.Merge(m, src)
}
func (m *Duration) XXX_Size() int {
	return xxx_messageInfo_Duration.Size(m)
}
func (m *Duration) XXX_DiscardUnknown() {
	xxx_messageInfo_Duration.DiscardUnknown(m)
}

var xxx_messageInfo_Duration proto.InternalMessageInfo

func (m *Duration) GetProtoDuration() *duration.Duration {
	if m != nil {
		return m.ProtoDuration
	}
	return nil
}

func init() {
	proto.RegisterType((*Time)(nil), "chrono.Time")
	proto.RegisterType((*Duration)(nil), "chrono.Duration")
}

func init() { proto.RegisterFile("chrono.proto", fileDescriptor_2fd0f9191623b5fb) }

var fileDescriptor_2fd0f9191623b5fb = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0x28, 0xca,
	0xcf, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0xa4, 0xe4, 0xd3, 0xf3,
	0xf3, 0xd3, 0x73, 0x52, 0xf5, 0xc1, 0xa2, 0x49, 0xa5, 0x69, 0xfa, 0x25, 0x99, 0xb9, 0xa9, 0xc5,
	0x25, 0x89, 0xb9, 0x05, 0x10, 0x85, 0x52, 0x72, 0xe8, 0x0a, 0x52, 0x4a, 0x8b, 0x12, 0x4b, 0x32,
	0xf3, 0xf3, 0x20, 0xf2, 0x4a, 0x8e, 0x5c, 0x2c, 0x21, 0x99, 0xb9, 0xa9, 0x42, 0x96, 0x5c, 0x5c,
	0x60, 0x81, 0x78, 0x90, 0x01, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x52, 0x7a, 0x10, 0xcd,
	0x7a, 0x30, 0xcd, 0x7a, 0x21, 0x30, 0xd3, 0x83, 0x38, 0xc1, 0x62, 0x20, 0xbe, 0x92, 0x0f, 0x17,
	0x87, 0x0b, 0xd4, 0x50, 0x21, 0x07, 0x2e, 0x3e, 0x88, 0x31, 0x30, 0x6b, 0xa0, 0x46, 0x49, 0x62,
	0x18, 0x05, 0xd3, 0x12, 0xc4, 0x0b, 0x16, 0x82, 0x71, 0x9d, 0x38, 0xa2, 0xa0, 0x7e, 0x4b, 0x62,
	0x03, 0x4b, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xa3, 0x9c, 0x0a, 0xfa, 0x00, 0x00,
	0x00,
}
